### ISSUE TITLE
Add a CONTRIBUTING.md file with contribution guidelines

### ISSUE THREAD

**Issue by Furchin** [builtforme/swatchjs#31]
Per https://hacktoberfest.digitalocean.com/#resources, we should document some contribution guidelines; there's no reason these couldn't be contributed themselves!

**Comment by shindakun** [comment]
@Furchin I figured I could grab this one since it's small. I used a fairly generic contribution.md - one question before I create the PR, the Enforcement section calls for an email address originally. If you don't want one on there it could always be a link to the GitHub issues page I suppose.

https://github.com/shindakun/swatchjs/blob/hacktober-add-contrib/CONTRIBUTING.md

**Comment by Furchin** [comment]
Our profile lists `hello@builtforme.tech` as the email so feel free to use that one. Thanks!

Looking at your template, I'd rather focus on a brief concise set of instructions on how to contribute rather than a code of conduct which addresses a problem we don't currently have (and I hope we never do). Maybe something akin to https://github.com/builtforme/CodeBnb/blob/master/CONTRIBUTING.md?

**Comment by shindakun** [comment]
Indeed, looking through a few more repos it seems many have pushed a CoC out to a separate file, if they have decided one is needed. It does add quite a bit of text to the contrib file, I'll get something else worked up in the next day or so.
